spring:
  application:
    name: auction-inventory-management
  datasource:
    url: jdbc:mysql://localhost:3306/auction-inventory
    username: root
    password: verysecret
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

